import { OrganizationSwitcher, UserButton, useOrganizationList, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { ReactNode } from "react";

const Home: NextPage = () => {
  const { isLoaded, isSignedIn, user } = useUser();

  if (!isLoaded || !isSignedIn) {
    return null;
  }

  return (
    <>
      <Head>
        <title>G7 Orgs Starter</title>
        <meta
          name="description"
          content="G7 - Generated by create-t3-app & clerk"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <NavbarLayout>
        <main className="flex min-h-screen flex-col items-center justify-center">
          <OrganizationList />
        </main>
      </NavbarLayout>
    </>
  );
};

export default Home;

const OrganizationList = () => {
  const { organizationList, isLoaded, setActive } = useOrganizationList();

  if (!isLoaded) {
    // show loading state
    return null;
  }

  return (
    <div>
      <h2>Your organizations</h2>
      {organizationList.length === 0 ? (
        <div>You do not belong to any organizations yet.</div>
      ) : (
        <ul>
          {organizationList.map(({ organization, membership }) => (
            <li key={organization.id}>
              <p>Name: {organization.name}</p>
              <p>Your role: {membership.role}</p>
              <button /* onClick={() => setActive(organization.id)} */>Make active</button>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
};

function NavbarLayout({ children }: { children: ReactNode }) {
  return (
    <div className="h-full min-h-screen w-full bg-neutral-100">
      <Navbar />
    </div>
  );
}

function Navbar() {
  return (
    <div className="flex h-16 w-full flex-row items-center justify-between border-b border-[#EAEAEA] bg-white px-6 py-3">
      {/* navbar start */}
      <div className="flex flex-row items-center justify-start space-x-4">
        <Logo />

        <div>
          <div className="text-[#EAEAEA]">
            <svg
              data-testid="geist-icon"
              fill="none"
              height="32"
              shapeRendering="geometricPrecision"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="1"
              viewBox="0 0 24 24"
              width="32">
              <path d="M16.88 3.549L7.12 20.451" />
            </svg>
          </div>
        </div>

        <div className="translate-y-[2px]">
          <OrganizationSwitcher />
        </div>
      </div>

      {/* navbar navigation */}
      {/* <div>navigation</div> */}

      {/* navbar end */}
      <div className="flex flex-row items-center justify-end space-x-4">
        <UserButton />
      </div>
    </div>
  );
}

function Logo() {
  return (
    <Link href="/">
      <div className="fill-black">
        <svg
          aria-label="Vercel Logo"
          // fill="#FFFFFF"
          viewBox="0 0 75 65"
          height="26"
          data-testid="dashboard/logo">
          <path d="M37.59.25l36.95 64H.64l36.95-64z"></path>
        </svg>
      </div>
    </Link>
  );
}
